// <auto-generated />
using System;
using EcoEnergyRazorProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EcoEnergyRazorProject.Migrations
{
    [DbContext(typeof(AplicationDbContext))]
    [Migration("20250318113800_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EcoEnergyRazorProject.Models.ConsumAigua", b =>
                {
                    b.Property<int>("CodiComarca")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodiComarca"));

                    b.Property<int>("ActivitatsFonts")
                        .HasColumnType("int");

                    b.Property<int>("Any")
                        .HasColumnType("int");

                    b.Property<string>("Comarca")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Consum")
                        .HasColumnType("float");

                    b.Property<int>("DomesticXarxa")
                        .HasColumnType("int");

                    b.Property<int>("Poblacio")
                        .HasColumnType("int");

                    b.Property<int>("Total")
                        .HasColumnType("int");

                    b.HasKey("CodiComarca");

                    b.ToTable("ConsumsAigua");
                });

            modelBuilder.Entity("EcoEnergyRazorProject.Models.IndicadorEnergetic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("CCAC_GasoilA")
                        .HasColumnType("float");

                    b.Property<double>("CCAC_GasolinaAuto")
                        .HasColumnType("float");

                    b.Property<double>("CDEEBC_ConsumAux")
                        .HasColumnType("float");

                    b.Property<double>("CDEEBC_ConsumBomb")
                        .HasColumnType("float");

                    b.Property<double>("CDEEBC_DemandaElectr")
                        .HasColumnType("float");

                    b.Property<double>("CDEEBC_ProdBruta")
                        .HasColumnType("float");

                    b.Property<double>("CDEEBC_ProdDisp")
                        .HasColumnType("float");

                    b.Property<double>("CDEEBC_ProdNeta")
                        .HasColumnType("float");

                    b.Property<double>("CDEEBC_SaldoIntercanviElectr")
                        .HasColumnType("float");

                    b.Property<double>("CDEEBC_TotVendesXarxaCentral")
                        .HasColumnType("float");

                    b.Property<double>("CDEEBC_TotalEBCMercatLliure")
                        .HasColumnType("float");

                    b.Property<double>("CDEEBC_TotalEBCMercatRegulat")
                        .HasColumnType("float");

                    b.Property<double>("DGGN_ConsumGNCentrTerm")
                        .HasColumnType("float");

                    b.Property<double>("DGGN_DistrAlimGNL")
                        .HasColumnType("float");

                    b.Property<double>("DGGN_PuntFrontEnagas")
                        .HasColumnType("float");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<double?>("FEEI_AlimBegudaTabac")
                        .HasColumnType("float");

                    b.Property<double?>("FEEI_AltresIndus")
                        .HasColumnType("float");

                    b.Property<double?>("FEEI_AltresMatConstr")
                        .HasColumnType("float");

                    b.Property<double?>("FEEI_CimentsCalGuix")
                        .HasColumnType("float");

                    b.Property<double?>("FEEI_ConsObrPub")
                        .HasColumnType("float");

                    b.Property<double?>("FEEI_ConstrMedTrans")
                        .HasColumnType("float");

                    b.Property<double?>("FEEI_IndusVidre")
                        .HasColumnType("float");

                    b.Property<double?>("FEEI_Metalurgia")
                        .HasColumnType("float");

                    b.Property<double?>("FEEI_PastaPaperCartro")
                        .HasColumnType("float");

                    b.Property<double?>("FEEI_QuimPetroquim")
                        .HasColumnType("float");

                    b.Property<double?>("FEEI_RestaTransforMetal")
                        .HasColumnType("float");

                    b.Property<double?>("FEEI_SiderFoneria")
                        .HasColumnType("float");

                    b.Property<double?>("FEEI_TextilConfecCuirCalçat")
                        .HasColumnType("float");

                    b.Property<double?>("FEE_Domestic")
                        .HasColumnType("float");

                    b.Property<double?>("FEE_Energetic")
                        .HasColumnType("float");

                    b.Property<double?>("FEE_Industria")
                        .HasColumnType("float");

                    b.Property<double?>("FEE_Primari")
                        .HasColumnType("float");

                    b.Property<double?>("FEE_Terciari")
                        .HasColumnType("float");

                    b.Property<double>("PBEE_Carbo")
                        .HasColumnType("float");

                    b.Property<double>("PBEE_CiclComb")
                        .HasColumnType("float");

                    b.Property<double>("PBEE_FuelOil")
                        .HasColumnType("float");

                    b.Property<double>("PBEE_GasNat")
                        .HasColumnType("float");

                    b.Property<double>("PBEE_Hidroelectr")
                        .HasColumnType("float");

                    b.Property<double>("PBEE_Nuclear")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("IndicadorsEnergetics");
                });

            modelBuilder.Entity("EcoEnergyRazorProject.Models.Simulacio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Cost")
                        .HasColumnType("float");

                    b.Property<double>("CostTotal")
                        .HasColumnType("float");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<double>("Energia")
                        .HasColumnType("float");

                    b.Property<double>("EntradaEnergia")
                        .HasColumnType("float");

                    b.Property<double>("Preu")
                        .HasColumnType("float");

                    b.Property<double>("PreuTotal")
                        .HasColumnType("float");

                    b.Property<double>("Rati")
                        .HasColumnType("float");

                    b.Property<string>("Tipus")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Simulacions");
                });
#pragma warning restore 612, 618
        }
    }
}
